### ISSUE TITLE
parsing problems: `@` in field (email addresses) and multi-line fields

### ISSUE THREAD

**Issue by kleinschmidt** [ropensci/bib2df#16]
I've run into a few problems parsing my .bib files with this.  First, parsing fails for any field that has an `@` anywhere in it (e.g., as part of an email address).  Second, it fails for multi-line fields (like the `annote` fields that are auto-exported by Mendeley).  Neither of these causes bibtex itself to complain so they are at least de facto supported.  Fixing the first probably isn't so difficult, but fixing the second might be more challenging given how the reading function works (need a pass to combine lines with un-terminated strings/fields).

**Comment by ottlngr** [comment]
Thanks for your message.

After a quick research `annonate` seems not to be a standard BibTex field, but is supported. So at least this field should not break `bib2df()`. The '@' problem should be an easy fix.

Could you provide a sample file so that I can reproduce the problems? What is the output of `bib2df()` when parsing your file?

**Comment by emilioxavier** [comment]
I have a similar problem but the '@' is within the title. Attached is a bibtex formatted file with four examples.

The `bib2df()` out put is:
```
Some BibTeX entries may have been dropped.
            The result could be malformed.
            Review the .bib file and make sure every single entry starts
            with a '@'.
Column `YEAR` contains character strings.
              No coercion to numeric applied.
```

It appears to result in a double entry for the `BIBTEXKEY` with an '@' in the title while other entries are correct.

Please let me know if you need additional information.

[titles_with_at_symbols.txt](https://github.com/ropensci/bib2df/files/1523885/titles_with_at_symbols.txt)

**Comment by ottlngr** [comment]
Thanks for your message, @emilioxavier . I think I can fix the issues with an '@' in BibTex fields soon.

**Comment by emilioxavier** [comment]
You're very welcome! Let me know if you would like me to test the fix.

**Comment by ottlngr** [comment]
@kleinschmidt 
This problem should be fixed now. I added unit tests that keep an eye on this scenario.
Please try the `dev` branch of `bib2df`:

`devtools::install_github("ropensci/bib2df", ref = "dev")`

**Comment by ottlngr** [comment]
Merged into `master`.
