### ISSUE TITLE
parsing problems: = symbol

### ISSUE THREAD

**Issue by rungec** [ropensci/bib2df#17]
Hi, I've run into a problem reading in references where abstract field contains an equals symbol = the preceeding abstract text is read in as a column header.
e.g.
"high genetic differentiation (F st = 0.043"
ends up as a new column header "HIGH.GENETIC.DIFFERENTIATION..F.ST"

**Comment by emilioxavier** [comment]
I have not been able to recreate this problem. For me, abstracts of interest often have equals signs `=`. @rungec could you please provide an example file?

Thank you

**Comment by rungec** [comment]
Weird! Here's the file I was using. It's a bibtex download from Web of Science
[WOS_2_core_references_a.zip](https://github.com/ropensci/bib2df/files/1619889/WOS_2_core_references_a.zip)

**Comment by emilioxavier** [comment]
Thank you @rungec for the bibtex file. There appears to be 500 references within the file. Three references do not include an abstract; once imported using `bib2df`. Checking these references within the original bibtex file indicates they original did _not_ have an abstract. Could you please indicate which reference is causing the problem and include the returned error?

I am using a [forked and patched version of `bib2df`](https://github.com/emilioxavier/bib2df) (the pull request is awaiting approval) and did not experience any errors.

**Comment by ottlngr** [comment]
@rungec 
This problem should be fixed now. I added unit tests that keep an eye on this scenario.
Please try the `dev` branch of `bib2df`:

`devtools::install_github("ropensci/bib2df", ref = "dev")`

**Comment by ottlngr** [comment]
Merged into `master`.
