### ISSUE TITLE
Package removed from CRAN

### ISSUE THREAD

**Issue by MahShaaban** [ropensci/bib2df#28]
It looks like the package was removed from CRAN for some reason. Is there a plan to resubmit the package in the near future?

**Comment by ottlngr** [comment]
Hi, yes definitely. I will soon have a look why this happened (again).

Sorry for the inconveniece!

**Comment by maelle** [comment]
:wave: @ottlngr, do you need any help with the CRAN stuff?

**Comment by maelle** [comment]
I :eyes: https://cran-archive.r-project.org/web/checks/2019-04-02_check_results_bib2df.html

Not sure which URL was the problem, but why read .bib from gists instead of storing them in inst/extdata btw?

**Comment by ottlngr** [comment]
Hey @maelle , I think I don't need any help regarding the 'how', but regarding the 'when' ... I'm not sure if can have a closer look before the weekend. But you're right, the Gist thing is a potential problem.

**Comment by maelle** [comment]
Oh I think it is fine if you wait a few days 🙂

**Comment by ottlngr** [comment]
Ok, `bib2df` is on its way to CRAN again.
