### ISSUE TITLE
`as_data_frame()` was deprecated in tibble 2.0.0.Y

### ISSUE THREAD

**Issue by rkoenker** [ropensci/bib2df#58]
You probably have already seen this, but if not:  I'm getting:
Warning messages:
1: `as_data_frame()` was deprecated in tibble 2.0.0.
ℹ Please use `as_tibble()` (with slightly different semantics) to convert to a tibble, or
  `as.data.frame()` to convert to a data frame.
ℹ The deprecated feature was likely used in the bib2df package.
  Please report the issue to the authors.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated. 
2: In bib2df_tidy(bib, separate_names) : NAs introduced by coercion

**Comment by giabaio** [comment]
Can you produce a more structure example for where you've seen this problem?

**Comment by rkoenker** [comment]
I thought that the warning was fairly clear:  Somewhere in bib2df_tidy you need to change as_data_frame to as.data.frame.

**Comment by giabaio** [comment]
`[bib2df_tidy](https://github.com/ropensci/bib2df/blob/main/R/bib2df_tidy.R)` doesn't call `as_data_frame` at all... I will look into this later, though.

**Comment by giabaio** [comment]
I actually couldn't reproduce this. Using
```
other attached packages:
[1] bib2df_1.1.2.0
```
the test based on 
```
bib2df(system.file("extdata", "bib2df_testfile_3.bib", package = "bib2df"))
```
doesn't produce any error/warning. What was the actual code you were using when you get the warning?

**Comment by rkoenker** [comment]
I get the same warning I reported earlier with your test, I'm running bib2df_1.1.1  though, which is the version on CRAN

**Comment by giabaio** [comment]
Can you please try to update to the newest version 
```
remotes::install_github("ropensci/bib2df")
```
and see if this persists? (It shouldn't...)

**Comment by rkoenker** [comment]
Yes, that is fine with the new version, but you can't expect users to know about versions on GitHub.  You should submit a new version to CRAN.

**Comment by SimonGreenhill** [comment]
yes, it was fixed [3 years ago](https://github.com/ropensci/bib2df/commit/2f9678d6c356000b7633d94997eed8d71694db06) -- can we get a new release on CRAN please?
